# .github/actions/authenticate-gcp/action.yaml
name: 'Authenticate to Google Cloud'
inputs:
  workload_identity_provider:
    required: true
  service_account:
    required: true
runs:
  using: 'composite'
  steps:
    - uses: 'google-github-actions/auth@v2.0.0'
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}
        access_token_lifetime: 1800 # 30 min
