name: Build

env:
  AWS_REGION: us-east-1
  WORKING_DIRECTORY: app

on:
  push:
    branches:
      - main
    paths:
      - app/**

  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        type: choice
        options:
          - 'build and push'
        default: 'build and push' 

jobs:
  build-and-deploy:
    permissions:
      contents: 'write'
      id-token: 'write'
      pull-requests: 'write'
    runs-on: ubuntu-latest
    container:
      image: hugomods/hugo:go

    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: true
        submodules: recursive

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5.0.0
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Hugo build
      shell: bash
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: |
        hugo --minify

    - name: Sync public directory with S3 bucket
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: |
        aws s3 sync public/ s3://${{ secrets.PORTFOLIO_BUCKET_NAME }}/ --delete --exact-timestamps


    - name: Invalidate CloudFront cache
      if: success()
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
          --paths "/*"
