name: "Terraform Infra"

env:
  WORKLOAD_IDENTITY: 'projects/307684202109/locations/global/workloadIdentityPools/workload-identity-pool/providers/github-thakurnishu'
  SERVICE_ACCOUNT: 'tf-apply-nishantlabs@org-identity-hub-471410.iam.gserviceaccount.com'
  BUCKET_NAME: 'nishantlabs_terraform_statefiles'
  PREFIX: 'portfolio'
  TERRAFORM_VERSION: '1.9.6'
  GCLOUD_SDK_VERSION: '>= 363.0.0'
  WORKING_DIRECTORY: 'infra'

on:
  push:
    branches: [ "main" ]
    paths:
      - 'infra/**'
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        type: choice
        options:
          - 'destroy'
          - 'create'
          - 'plan'
        default: 'plan' 
jobs:
  Terraform-Infra:
    permissions:
      contents: 'write'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - id: 'applierAuth'
        uses: ./.github/actions/authenticate-gcp
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY }}
          service_account: ${{ env.SERVICE_ACCOUNT }} 

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - id: fmt
        shell: bash
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: terraform fmt -check

      - id: init
        shell: bash
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          terraform init \
                -reconfigure \
                -backend-config="bucket=${{ env.BUCKET_NAME }}" \
                -backend-config="prefix=${{ env.PREFIX }}" 

      - id: validate
        shell: bash
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: terraform validate -no-color

      - id: plan
        name: Terraform Plan
        if: github.event.inputs.action == 'plan'
        shell: bash
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          terraform plan -input=false -no-color

      - id: apply
        name: Terraform Apply
        if: github.event.inputs.action == 'create' || github.ref == 'refs/heads/main'
        shell: bash
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          terraform apply -input=false -auto-approve -no-color

      - id: destroy
        name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        shell: bash
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          terraform destroy -input=false -auto-approve -no-color
